name:                montgomery
version:             0.1.0.0
github:              "ocheron/montgomery"
license:             BSD3
author:              "Olivier Chéron"
maintainer:          "olivier.cheron@gmail.com"
copyright:           "2022 Olivier Chéron"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Experiments about arithmetic in Montgomery form.
category:            Crypto

description:         Experiments about arithmetic in Montgomery form.

dependencies:
- base >= 4.11 && < 5

ghc-options:
- -Wall

library:
  source-dirs: src
  exposed-modules:
  - Numeric.Montgomery
  dependencies:
  - basement
  - deepseq

tests:
  montgomery-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - montgomery
    - tasty
    - tasty-quickcheck

benchmarks:
  montgomery-bench:
    main:                Bench.hs
    source-dirs:         benchs
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - montgomery
    - cryptonite
    - gauge
